// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview A translation AI agent that translates a string from one language to another.
 *
 * - translateString - A function that handles the string translation process.
 * - TranslateStringInput - The input type for the translateString function.
 * - TranslateStringOutput - The return type for the translateString function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TranslateStringInputSchema = z.object({
  text: z.string().describe('The text to translate.'),
  sourceLanguage: z.string().describe('The source language of the text.'),
  targetLanguage: z.string().describe('The target language to translate to.'),
});
export type TranslateStringInput = z.infer<typeof TranslateStringInputSchema>;

const TranslateStringOutputSchema = z.object({
  translatedText: z.string().describe('The translated text.'),
});
export type TranslateStringOutput = z.infer<typeof TranslateStringOutputSchema>;

export async function translateString(input: TranslateStringInput): Promise<TranslateStringOutput> {
  return translateStringFlow(input);
}

const translateStringPrompt = ai.definePrompt({
  name: 'translateStringPrompt',
  input: {schema: TranslateStringInputSchema},
  output: {schema: TranslateStringOutputSchema},
  prompt: `You are a professional translator.
Translate the following text from {{sourceLanguage}} to {{targetLanguage}}:

{{text}}`,
});

const translateStringFlow = ai.defineFlow(
  {
    name: 'translateStringFlow',
    inputSchema: TranslateStringInputSchema,
    outputSchema: TranslateStringOutputSchema,
  },
  async input => {
    const {output} = await translateStringPrompt(input);
    return output!;
  }
);
