/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Dq3q4jYf2aZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"
import { ArrowRight, Bot, FileJson, Languages } from "lucide-react"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <Languages className="h-6 w-6" />
          <span className="sr-only">XCStrings Translator</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="/translate"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Translate
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="relative w-full py-20 md:py-32 lg:py-40">
          <div className="absolute inset-0 bg-gradient-to-t from-background to-transparent z-10" />
           <div className="absolute inset-0 grainy z-0" />
          <div className="container px-4 md:px-6 text-center relative z-20">
            <div className="max-w-3xl mx-auto space-y-4">
              <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
                Translate Your Xcode Strings with AI
              </h1>
              <p className="text-lg text-muted-foreground md:text-xl">
                Effortlessly upload your .xcstrings file, and let our AI handle the translations. A simple, fast, and
                developer-friendly way to localize your iOS, macOS, and visionOS apps.
              </p>
              <div>
                <Button asChild size="lg">
                  <Link href="/translate" prefetch={false}>
                    Get Started <ArrowRight className="ml-2 h-5 w-5" />
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </section>
        <section id="features" className="w-full py-12 md:py-24 lg:py-32 bg-secondary/50">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Key Features</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Streamline Your Localization Workflow</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Our translator is built to make your life easier. From file import to AI-powered translation, every step is optimized for speed and simplicity.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:grid-cols-3 lg:gap-12 mt-12">
              <div className="grid gap-1 text-center">
                <div className="flex justify-center">
                  <FileJson className="h-10 w-10 mb-2" />
                </div>
                <h3 className="text-lg font-bold">Easy File Handling</h3>
                <p className="text-sm text-muted-foreground">
                  Import your .xcstrings file with a single click. View all your keys and existing translations in a clean, organized table.
                </p>
              </div>
              <div className="grid gap-1 text-center">
                <div className="flex justify-center">
                    <Bot className="h-10 w-10 mb-2" />
                </div>
                <h3 className="text-lg font-bold">AI-Powered Translation</h3>
                <p className="text-sm text-muted-foreground">
                  Leverage the power of Google's Gemini to automatically translate new or untranslated entries into any language you choose.
                </p>
              </div>
              <div className="grid gap-1 text-center">
                <div className="flex justify-center">
                    <Languages className="h-10 w-10 mb-2" />
                </div>
                <h3 className="text-lg font-bold">Side-by-Side View</h3>
                <p className="text-sm text-muted-foreground">
                  See all languages in columns next to each other, making it easy to compare translations and spot inconsistencies.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section id="faq" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Frequently Asked Questions</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Have questions? We've got answers. Here are some of the most common questions we get.
                </p>
              </div>
            </div>
            <div className="mx-auto max-w-3xl mt-12">
              <Accordion type="single" collapsible>
                <AccordionItem value="item-1">
                  <AccordionTrigger>Is my data secure?</AccordionTrigger>
                  <AccordionContent>
                    Yes, absolutely. Your .xcstrings file and API key are processed entirely in your browser. Nothing is ever stored on our servers. Your API key is stored in your browser's local storage for convenience.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                  <AccordionTrigger>Which AI model do you use?</AccordionTrigger>
                  <AccordionContent>
                    We use the Google Gemini family of models via Genkit to provide high-quality translations. You must provide your own Gemini API key to use the translation feature.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                  <AccordionTrigger>Can I use this for free?</AccordionTrigger>
                  <AccordionContent>
                    Yes, this tool is completely free to use. You are only responsible for the costs associated with your own Google Gemini API key usage.
                  </AccordionContent>
                </AccordionItem>
                 <AccordionItem value="item-4">
                  <AccordionTrigger>What is an .xcstrings file?</AccordionTrigger>
                  <AccordionContent>
                    It's the standard format for string localization introduced by Apple in Xcode 15. It's a JSON-based format that organizes strings and their translations for different languages in your app.
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </div>
          </div>
        </section>
        
        <section className="w-full py-12 md:py-24 lg:py-32 bg-secondary/50">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Ready to Simplify Your Localization?
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Stop juggling files and manual translations. Try it now and see how much time you can save.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
               <Button asChild size="lg">
                  <Link href="/translate" prefetch={false}>
                    Translate My Strings
                  </Link>
                </Button>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 XCStrings Translator. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#features" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Features
          </Link>
          <Link href="#faq" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            FAQ
          </Link>
        </nav>
      </footer>
    </div>
  )
}
